%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.Width: 640
Camera.Height: 480
Camera.fx: 517.306408
Camera.fy: 516.469215
Camera.cx: 318.643040
Camera.cy: 255.313989

Camera.k1: 0.262383
Camera.k2: -0.953104
Camera.p1: -0.005358
Camera.p2: 0.002628
Camera.k3: 1.163314

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor
DepthMapFactor: 1000

# ROS
ROS.CameraTopic: "/camera/color/image_raw"
ROS.DepthTopic: "/camera/aligned_depth_to_color/image_raw"
ROS.IMUTopic: "/imu_data"
ROS.BaseFrame: "odom"
ROS.CameraFrame: "camera_link"
ROS.UseImagesTimeStamps: true
